package actions

import (
	"fmt"

	"bribebybytes.in/gameaholic/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (PlayerTimeline)
// DB Table: Plural (player_timelines)
// Resource: Plural (PlayerTimelines)
// Path: Plural (/player_timelines)
// View Template Folder: Plural (/templates/player_timelines/)

// PlayerTimelinesResource is the resource for the PlayerTimeline model
type PlayerTimelinesResource struct {
	buffalo.Resource
}

// List gets all PlayerTimelines. This function is mapped to the path
// GET /player_timelines
func (v PlayerTimelinesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	playerTimelines := &models.PlayerTimelines{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all PlayerTimelines from the DB
	if err := q.All(playerTimelines); err != nil {
		return err
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, playerTimelines))
}

// Show gets the data for one PlayerTimeline. This function is mapped to
// the path GET /player_timelines/{player_timeline_id}
func (v PlayerTimelinesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty PlayerTimeline
	playerTimeline := &models.PlayerTimeline{}

	// To find the PlayerTimeline the parameter player_timeline_id is used.
	if err := tx.Find(playerTimeline, c.Param("player_timeline_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, playerTimeline))
}

// New renders the form for creating a new PlayerTimeline.
// This function is mapped to the path GET /player_timelines/new
func (v PlayerTimelinesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.PlayerTimeline{}))
}

// Create adds a PlayerTimeline to the DB. This function is mapped to the
// path POST /player_timelines
func (v PlayerTimelinesResource) Create(c buffalo.Context) error {
	// Allocate an empty PlayerTimeline
	playerTimeline := &models.PlayerTimeline{}

	// Bind playerTimeline to the html form elements
	if err := c.Bind(playerTimeline); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(playerTimeline)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, playerTimeline))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "playerTimeline.created.success"))
	// and redirect to the player_timelines index page
	return c.Render(201, r.Auto(c, playerTimeline))
}

// Edit renders a edit form for a PlayerTimeline. This function is
// mapped to the path GET /player_timelines/{player_timeline_id}/edit
func (v PlayerTimelinesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty PlayerTimeline
	playerTimeline := &models.PlayerTimeline{}

	if err := tx.Find(playerTimeline, c.Param("player_timeline_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, playerTimeline))
}

// Update changes a PlayerTimeline in the DB. This function is mapped to
// the path PUT /player_timelines/{player_timeline_id}
func (v PlayerTimelinesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty PlayerTimeline
	playerTimeline := &models.PlayerTimeline{}

	if err := tx.Find(playerTimeline, c.Param("player_timeline_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind PlayerTimeline to the html form elements
	if err := c.Bind(playerTimeline); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(playerTimeline)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, playerTimeline))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "playerTimeline.updated.success"))
	// and redirect to the player_timelines index page
	return c.Render(200, r.Auto(c, playerTimeline))
}

// Destroy deletes a PlayerTimeline from the DB. This function is mapped
// to the path DELETE /player_timelines/{player_timeline_id}
func (v PlayerTimelinesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty PlayerTimeline
	playerTimeline := &models.PlayerTimeline{}

	// To find the PlayerTimeline the parameter player_timeline_id is used.
	if err := tx.Find(playerTimeline, c.Param("player_timeline_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(playerTimeline); err != nil {
		return err
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", T.Translate(c, "playerTimeline.destroyed.success"))
	// Redirect to the player_timelines index page
	return c.Render(200, r.Auto(c, playerTimeline))
}
